### ISSUE TITLE
Issue while editing already saved medicine

### ISSUE THREAD

**Issue by Lipsaray** [nithyakonda/LupusApp#3]
1) Add a medicine and save it.
2) Add a second medicine and save it.
2) Go to the Medicine list and click on the second medicine to edit.
3) Add new medicine and save.
4) Go to medicine listview.

Expected: 1st medicine and new 2nd medicine.
Actual: new 2nd medicine appears twice.

**Comment by nithyakonda** [comment]
Appears to be fixed.

**Comment by Lipsaray** [comment]
Works
