### ISSUE TITLE
Navigate from Home page to Activity sense page

### ISSUE THREAD

**Issue by Lipsaray** [nithyakonda/LupusApp#9]
Expected: Land on Activity Sensing page
Actual: Land on Activity Sensing page and step count starts automatically

**Comment by nithyakonda** [comment]
I reproduced it in a different way.
1. Go to Home
2. Click on Activity Sensing
3. Start and Stop
4. Go back to Home
5. Click on Activity Sensing

Then step count starts automatically.

**Comment by nithyakonda** [comment]
Fixed

**Comment by Lipsaray** [comment]
Works Fine.
